sudo: required
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform
  - build-tools-24.0.0
  - android-24
  - extra-google-google_play_services
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository